app = "bikeberi-service-control"
primary_region = "waw"

[build]
  dockerfile = "Dockerfile"

[env]
  BIKEBERI_COOKIE_SECURE = "true"
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[mounts]
  source = "bikeberi_data"
  destination = "/data"
